# Generated by Django 4.2.13 on 2024-07-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_followers_likepost'),
        ('userauth', '0005_alter_likepost_post_id_alter_post_id_and_more'),
        ('userauth', '0006_remove_profile_id_profile_id_user_and_more'),
    ]

    operations = [
    ]
